version: '3'

services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: houzhongxu/autogen-dev:latest  # 添加这行
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    # 如果需要其他配置，比如端口映射等，可以在这里添加
